name: HTML Deploy
on:
  push: # main Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@main

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm s3://admin.copang.xyz --recursive
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            . s3://admin.copang.xyz
